import ProjectDescription

// Tuist's autogenerated schemes are one-per-project, so Xcode's Test navigator only lists the
// tests of the currently selected scheme (e.g. selecting "App" only shows AppTests/AppUITests).
// This scheme aggregates every unit test target so all tests are visible and runnable in one
// place; the per-module `tuist test <SchemeName>` workflow in CLAUDE.md is unaffected.
let allUnitTestTargets: [TargetReference] = [
    .project(path: .relativeToRoot("Projects/App"), target: "AppTests"),
    .project(path: .relativeToRoot("Projects/Core/DesignSystem"), target: "CoreDesignSystemTests"),
    .project(path: .relativeToRoot("Projects/Core/Models"), target: "CoreModelsTests"),
    .project(path: .relativeToRoot("Projects/Core/Networking"), target: "CoreNetworkingTests"),
    .project(path: .relativeToRoot("Projects/Core/RASP"), target: "CoreRASPTests"),
    .project(path: .relativeToRoot("Projects/Core/SecureStorage"), target: "CoreSecureStorageTests"),
    .project(path: .relativeToRoot("Projects/Features/Auth"), target: "FeatureAuthTests"),
    .project(path: .relativeToRoot("Projects/Features/TopicDetail"), target: "FeatureTopicDetailTests"),
    .project(path: .relativeToRoot("Projects/Features/TopicsList"), target: "FeatureTopicsListTests"),
]

let workspace = Workspace(
    name: "BankingTechStack",
    projects: [
        "Projects/App",
        "Projects/Features/**",
        "Projects/Core/**",
    ],
    schemes: [
        .scheme(
            name: "AllTests",
            testAction: .targets(allUnitTestTargets.map { TestableTarget.testableTarget(target: $0) })
        ),
    ],
    additionalFiles: [
        "Workspace.swift",
        "Tuist.swift",
        "Tuist/ProjectDescriptionHelpers/Project+Module.swift",
        "Tuist/Package.swift",
    ]
)
